# Generated by Django 2.2.5 on 2019-09-06 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ada', '0012_auto_20190906_0850'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=250)),
                ('roles', multiselectfield.db.fields.MultiSelectField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Android', 'Android'), ('Data Science', 'Data Science'), ('Devops', 'Devops'), ('Embedded Systems', 'Embedded Systems'), ('iOS', 'iOS'), ('Machine Learning', 'Machine Learning'), ('Robotics', 'Robotics')], max_length=102)),
                ('linkedin', models.URLField()),
                ('portfolio', models.URLField()),
                ('github', models.URLField()),
                ('cv', models.FileField(upload_to=None)),
                ('skills', models.ManyToManyField(related_name='users', to='ada.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
