# Generated by Django 2.2.5 on 2019-09-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Android', 'Android'), ('Data Science', 'Data Science'), ('Devops', 'Devops'), ('Embedded Systems', 'Embedded Systems'), ('iOS', 'iOS'), ('Machine Learning', 'Machine Learning'), ('Robotics', 'Robotics')], max_length=50)),
                ('javascript', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('python', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('react', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('java', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('html', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('git', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('node', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('css', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('mysql', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('aws', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('cplusplus', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('postgresql', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('bash_shell', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('angular', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('react_native', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('mongodb', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('ruby_on_rails', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('php', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
                ('c', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hight', 'Hight')], max_length=50)),
            ],
        ),
    ]
