# Generated by Django 2.2.5 on 2019-09-11 17:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Android', 'Android'), ('Data Science', 'Data Science'), ('Devops', 'Devops'), ('Embedded Systems', 'Embedded Systems'), ('iOS', 'iOS'), ('Machine Learning', 'Machine Learning'), ('Robotics', 'Robotics')], max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('React', 'React'), ('Java', 'Java'), ('HTML', 'HTML'), ('Git', 'Git'), ('Node.js', 'Node.js'), ('CSS', 'CSS'), ('MySQL', 'MySQL'), ('Amazon Web Services (AWS)', 'Amazon Web Services (AWS)'), ('C++', 'C++'), ('PostgreSQL', 'PostgreSQL'), ('Bash/Shell', 'Bash/Shell'), ('Angular', 'Angular'), ('React Native', 'React Native'), ('MongoDB', 'MongoDB'), ('Ruby on Rails', 'Ruby on Rails'), ('PHP', 'PHP'), ('C', 'C')], max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='offer',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('React', 'React'), ('Java', 'Java'), ('HTML', 'HTML'), ('Git', 'Git'), ('Node.js', 'Node.js'), ('CSS', 'CSS'), ('MySQL', 'MySQL'), ('Amazon Web Services (AWS)', 'Amazon Web Services (AWS)'), ('C++', 'C++'), ('PostgreSQL', 'PostgreSQL'), ('Bash/Shell', 'Bash/Shell'), ('Angular', 'Angular'), ('React Native', 'React Native'), ('MongoDB', 'MongoDB'), ('Ruby on Rails', 'Ruby on Rails'), ('PHP', 'PHP'), ('C', 'C')], max_length=30), size=None),
        ),
    ]
