# Generated by Django 2.2.5 on 2019-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0002_auto_20190905_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmatch',
            name='angular',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='aws',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='bash_shell',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='c',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='cplusplus',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='css',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='git',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='html',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='java',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='javascript',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='mongodb',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='mysql',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='node',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='php',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='postgresql',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='python',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='react',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='react_native',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillmatch',
            name='ruby_on_rails',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50),
        ),
    ]
