# Generated by Django 2.2.5 on 2019-09-05 10:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0006_auto_20190905_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmatch',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Android', 'Android'), ('Data Science', 'Data Science'), ('Devops', 'Devops'), ('Embedded Systems', 'Embedded Systems'), ('iOS', 'iOS'), ('Machine Learning', 'Machine Learning'), ('Robotics', 'Robotics')], max_length=102),
        ),
    ]
