# Generated by Django 2.2.5 on 2019-09-05 10:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0007_auto_20190905_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmatch',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Frontend'), ('2', 'Backend'), ('3', 'Full Stack'), ('4', 'Android'), ('5', 'Data Science'), ('6', 'Devops'), ('7', 'Embedded Systems'), ('8', 'iOS'), ('9', 'Machine Learning'), ('0', 'Robotics')], max_length=4),
        ),
    ]
