# Generated by Django 2.2.5 on 2019-09-05 15:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0009_auto_20190905_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('jobtitle', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Android', 'Android'), ('Data Science', 'Data Science'), ('Devops', 'Devops'), ('Embedded Systems', 'Embedded Systems'), ('iOS', 'iOS'), ('Machine Learning', 'Machine Learning'), ('Robotics', 'Robotics')], default=None, max_length=50)),
                ('wage', models.IntegerField(max_length=10)),
                ('experience_in_years', models.IntegerField()),
                ('description_of_role', models.CharField(max_length=1000)),
                ('technologies', multiselectfield.db.fields.MultiSelectField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('React', 'React'), ('Java', 'Java'), ('HTML', 'HTML'), ('Git', 'Git'), ('Node.js', 'Node.js'), ('CSS', 'CSS'), ('MySQL', 'MySQL'), ('Amazon Web Services (AWS)', 'Amazon Web Services (AWS)'), ('C++', 'C++'), ('PostgreSQL', 'PostgreSQL'), ('Bash/Shell', 'Bash/Shell'), ('Angular', 'Angular'), ('React Native', 'React Native'), ('MongoDB', 'MongoDB'), ('Ruby on Rails', 'Ruby on Rails'), ('PHP', 'PHP'), ('C', 'C')], max_length=156)),
                ('qualifications', models.CharField(max_length=1000)),
                ('benefits', models.CharField(max_length=1000)),
                ('applications_received', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('React', 'React'), ('Java', 'Java'), ('HTML', 'HTML'), ('Git', 'Git'), ('Node.js', 'Node.js'), ('CSS', 'CSS'), ('MySQL', 'MySQL'), ('Amazon Web Services (AWS)', 'Amazon Web Services (AWS)'), ('C++', 'C++'), ('PostgreSQL', 'PostgreSQL'), ('Bash/Shell', 'Bash/Shell'), ('Angular', 'Angular'), ('React Native', 'React Native'), ('MongoDB', 'MongoDB'), ('Ruby on Rails', 'Ruby on Rails'), ('PHP', 'PHP'), ('C', 'C')], default=None, max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High')], default=None, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SkillMatch',
        ),
    ]
