# Generated by Django 2.2.5 on 2019-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0010_auto_20190905_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='wage',
            field=models.IntegerField(),
        ),
    ]
