# Generated by Django 2.2.5 on 2019-09-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0011_auto_20190905_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='companies.Company'),
        ),
    ]
